<?php
/**
 * QCD Redis.
 *
 * @author    410 Gone
 * @copyright 410 Gone
 * @license   Proprietary
 */

declare(strict_types=1);

namespace QcdGone\QcdRedis\Controller\Admin;

use QcdGone\QcdRedis\Cache\RedisConfigFactory;
use QcdGone\QcdRedis\Config\ConfigurationProvider;
use QcdGone\QcdRedis\Config\ConfigurationUpdater;
use QcdGone\QcdRedis\Form\CacheSettingsType;
use QcdGone\QcdRedis\Form\ConnectionType;
use QcdGone\QcdRedis\Service\CachePurger;
use QcdGone\QcdRedis\Service\CacheWarmer;
use QcdGone\QcdRedis\Service\DiagnosticsRunner;
use QcdGone\QcdRedis\Service\RedisConnectionFactory;
use QcdGone\QcdRedis\Service\StatisticsProvider;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Symfony admin controller backing the whole QCD Redis back office
 * (configuration forms + JSON endpoints for dashboard, statistics, diagnostics,
 * purge and warmup).
 *
 * It extends Symfony's AbstractController (stable across PrestaShop 8 and 9)
 * and renders Twig templates that extend the PrestaShop admin layout. Access is
 * gated by the admin firewall and the module tab; every route carries the admin
 * security token generated by the router.
 */
final class QcdRedisController extends AbstractController
{
    public function __construct(
        private readonly ConfigurationProvider $provider,
        private readonly ConfigurationUpdater $updater,
        private readonly RedisConnectionFactory $connectionFactory,
        private readonly StatisticsProvider $statistics,
        private readonly DiagnosticsRunner $diagnostics,
        private readonly CachePurger $purger,
        private readonly CacheWarmer $warmer,
    ) {
    }

    /**
     * Render the tabbed interface and handle the two configuration forms.
     */
    public function index(Request $request): Response
    {
        $raw = $this->provider->getRawValues();
        $connectionForm = $this->createForm(ConnectionType::class, $this->connectionData($raw));
        $cacheForm = $this->createForm(CacheSettingsType::class, $this->cacheData($raw));

        $connectionForm->handleRequest($request);
        if ($connectionForm->isSubmitted() && $connectionForm->isValid()) {
            $this->updater->saveConnection($connectionForm->getData());
            $this->addFlash('success', 'Connection settings saved.');

            return $this->redirectToRoute('qcdredis_admin_configure');
        }

        $cacheForm->handleRequest($request);
        if ($cacheForm->isSubmitted() && $cacheForm->isValid()) {
            $this->updater->saveCache($cacheForm->getData());
            $this->addFlash('success', 'Cache settings saved.');

            return $this->redirectToRoute('qcdredis_admin_configure');
        }

        return $this->render('@Modules/qcdredis/views/templates/admin/configure.html.twig', [
            'connectionForm' => $connectionForm->createView(),
            'cacheForm' => $cacheForm->createView(),
            'overview' => $this->statistics->getOverview(),
            'assetsUrl' => (defined('_MODULE_DIR_') ? _MODULE_DIR_ : '/modules/') . 'qcdredis/views/',
        ]);
    }

    public function testConnection(Request $request): JsonResponse
    {
        $raw = $this->provider->getRawValues();
        $password = (string) $request->request->get('password', '');

        $config = RedisConfigFactory::fromValues([
            RedisConfigFactory::KEY_HOST => (string) $request->request->get('host'),
            RedisConfigFactory::KEY_PORT => (int) $request->request->get('port'),
            RedisConfigFactory::KEY_DB => (int) $request->request->get('db'),
            RedisConfigFactory::KEY_TIMEOUT => (float) $request->request->get('timeout'),
            RedisConfigFactory::KEY_TLS => (bool) $request->request->get('tls'),
            RedisConfigFactory::KEY_PASSWORD => $password !== '' ? $password : (string) $raw[RedisConfigFactory::KEY_PASSWORD],
        ]);

        $connection = $this->connectionFactory->create($config);
        $ok = $connection->isAvailable();

        return $this->json([
            'success' => $ok,
            'message' => $ok ? 'Connection successful.' : ('Connection failed: ' . $connection->getLastError()),
        ]);
    }

    public function stats(): JsonResponse
    {
        return $this->json([
            'success' => true,
            'overview' => $this->statistics->getOverview(),
            'heavy_keys' => $this->statistics->getHeavyKeys(20),
            'average_ttl' => $this->statistics->getAverageTtl(),
        ]);
    }

    public function diagnostics(): JsonResponse
    {
        return $this->json(['success' => true, 'checks' => $this->diagnostics->run()]);
    }

    public function benchmark(): JsonResponse
    {
        return $this->json(['success' => true, 'benchmark' => $this->diagnostics->benchmark()]);
    }

    public function exportCsv(): Response
    {
        $response = new Response($this->statistics->toCsv());
        $response->headers->set('Content-Type', 'text/csv; charset=utf-8');
        $response->headers->set('Content-Disposition', 'attachment; filename="qcdredis-stats.csv"');

        return $response;
    }

    public function purge(Request $request): JsonResponse
    {
        $type = (string) $request->request->get('type', 'all');

        return match ($type) {
            'prefix' => $this->json(['success' => true, 'deleted' => $this->purger->purgeByPrefix((string) $request->request->get('prefix'))]),
            'tags' => $this->json(['success' => true, 'deleted' => $this->purger->purgeByTags(explode(',', (string) $request->request->get('tags')))]),
            'expired' => $this->json(['success' => true, 'expired_keys' => $this->purger->reportExpired()]),
            default => $this->json(['success' => true, 'deleted' => $this->purger->purgeAll()]),
        };
    }

    public function warmupBuild(Request $request): JsonResponse
    {
        /** @var string[] $types */
        $types = array_map('strval', (array) $request->request->all('types'));

        return $this->json(['success' => true, 'total' => $this->warmer->buildAndStoreQueue($types)]);
    }

    public function warmupBatch(Request $request): JsonResponse
    {
        $offset = (int) $request->request->get('offset');
        $size = max(1, min(20, (int) $request->request->get('size', 5)));
        $result = $this->warmer->warmStoredBatch($offset, $size);
        $result['success'] = true;

        return $this->json($result);
    }

    /**
     * @param array<string, mixed> $raw
     *
     * @return array<string, mixed>
     */
    private function connectionData(array $raw): array
    {
        return [
            'host' => $raw[RedisConfigFactory::KEY_HOST],
            'port' => (int) $raw[RedisConfigFactory::KEY_PORT],
            'password' => '',
            'db' => (int) $raw[RedisConfigFactory::KEY_DB],
            'timeout' => (float) $raw[RedisConfigFactory::KEY_TIMEOUT],
            'tls' => (bool) $raw[RedisConfigFactory::KEY_TLS],
        ];
    }

    /**
     * @param array<string, mixed> $raw
     *
     * @return array<string, mixed>
     */
    private function cacheData(array $raw): array
    {
        return [
            'enabled' => (bool) $raw[RedisConfigFactory::KEY_ENABLED],
            'ttl' => (int) $raw[RedisConfigFactory::KEY_TTL],
            'prefix' => $raw[RedisConfigFactory::KEY_PREFIX],
            'compression' => (bool) $raw[RedisConfigFactory::KEY_COMPRESSION],
            'compression_auto' => (bool) $raw[RedisConfigFactory::KEY_COMPRESSION_AUTO],
            'compression_threshold' => (int) $raw[RedisConfigFactory::KEY_COMPRESSION_THRESHOLD],
            'serializer' => $raw[RedisConfigFactory::KEY_SERIALIZER],
        ];
    }
}
