services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    QcdGone\QcdRedis\Config\ConfigurationProvider: ~
    QcdGone\QcdRedis\Config\ConfigurationUpdater: ~

    QcdGone\QcdRedis\Service\CachePurger: ~
    QcdGone\QcdRedis\Service\CacheWarmer: ~
    QcdGone\QcdRedis\Service\DiagnosticsRunner: ~
    QcdGone\QcdRedis\Service\RedisConnectionFactory: ~
    QcdGone\QcdRedis\Service\StatisticsProvider: ~

    QcdGone\QcdRedis\Form\CacheSettingsType: ~
    QcdGone\QcdRedis\Form\ConnectionType: ~

    QcdGone\QcdRedis\Controller\Admin\QcdRedisController:
        public: true
        tags: ['controller.service_arguments']
